# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: quay.io
  repository: rfcurated/zalando/postgres-operator
  tag: 1.15-jammy-scratch-fips-rfcurated
configConnectionPooler:
  connection_pooler_image: "quay.io/rfcurated/pgbouncer:1.25-jammy-fips-rfcurated"
configLogicalBackup:
  logical_backup_docker_image: "quay.io/rfcurated/zalando/postgres-operator/logical-backup:1.15-jammy-scratch-fips-rfcurated"
configGeneral:
  docker_image: "quay.io/rfcurated/zalando/spilo-17:4.0-p2-jammy-fips-rfcurated"
