# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

metrics:
  image: "cgr.dev/du-uds-defenseunicorns/prometheus-postgres-exporter-fips:0.16.0"
