# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: ghcr.io
  repository: zalando/postgres-operator
  tag: v1.14.0
configConnectionPooler:
  connection_pooler_image: "ghcr.io/cloudnative-pg/pgbouncer:1.24.1-23"
configLogicalBackup:
  logical_backup_docker_image: "ghcr.io/zalando/postgres-operator/logical-backup:v1.14.0"
configGeneral:
  docker_image: "ghcr.io/zalando/spilo-17:4.0-p2"
