# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: ghcr.io
  repository: zalando/postgres-operator
  tag: v1.13.0
configConnectionPooler:
  connection_pooler_image: "docker.io/bitnami/pgbouncer:1.23.1"
configLogicalBackup:
  logical_backup_docker_image: "ghcr.io/zalando/postgres-operator/logical-backup:v1.13.0"
configGeneral:
  docker_image: "ghcr.io/zalando/spilo-15:3.2-p1"
