name: Test

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    paths:
      - ".github/**"
      - "bundle/**"
      - "values/**"
      - "tasks/**"
      - "src/**"
      - "chart/**"
      - "tasks.yaml"
      - "zarf.yaml"
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [milestoned, opened, reopened, synchronize]


# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  id-token: write # Needed for OIDC-related operations.
  contents: read # Allows reading the content of the repository.
  pull-requests: read # Allows reading pull request metadata.

# Default settings for all run commands in the workflow jobs.
defaults:
  run:
    shell: bash -e -o pipefail {0} # Ensures that scripts fail on error and pipefail is set.

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install UDS CLI
        shell: bash
        # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
        run: brew install defenseunicorns/tap/uds@0.9.0
      - name: Run Formatting Checks
        run: uds run lint-check

  deploy:
    needs: lint-check
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    strategy:
      matrix:
        flavor: [upstream, registry1]
    name: Deploy ${{ matrix.flavor }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@264ec430c4079129870820e70c4439f3f3d57cbc

      - name: Iron Bank Login
        if: ${{ matrix.flavor == 'registry1' }}
        run: uds zarf tools registry login -u "${{secrets.IRON_BANK_ROBOT_USERNAME}}" -p "${{secrets.IRON_BANK_ROBOT_PASSWORD}}" registry1.dso.mil

      - name: Clean Runner
        if: ${{ matrix.flavor == 'registry1' }}
        uses: defenseunicorns/uds-common/.github/actions/clean-runner@264ec430c4079129870820e70c4439f3f3d57cbc

      - name: Create test bundle
        run: uds run create-test-bundle --set FLAVOR=${{ matrix.flavor }}

      - name: Setup cluster
        run: uds run setup-cluster

      - name: Deploy test bundle
        run: uds run deploy-test-bundle

      - name: Test package
        run: uds run test-package

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@264ec430c4079129870820e70c4439f3f3d57cbc
        with:
          suffix: '${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}'
